FROM node:22-slim

WORKDIR /app

COPY web/package*.json ./
RUN npm install

COPY web/ ./
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_API_URL=http://localhost:4000
RUN npm run build

EXPOSE 3000
ENV PORT=3000

CMD ["npm", "start"]
